# Generated by Django 5.2.7 on 2025-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="date_worked",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="hours_spent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
