# Generated by Django 5.2.7 on 2025-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0005_alter_entry_options_entry_exam_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="numeric_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
